use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::Instant;

use fjord_db::SqliteWorkspaceStore;
use fjord_git::GixGitBackend;
use fjord_ports::{GitBackend, RepoPath, WorkspaceStore};
use git2::{Repository, RepositoryInitOptions, Signature};

const MARKER_FILE: &str = ".fjord-synthetic-repo";

#[derive(Debug)]
struct Args {
    repo: PathBuf,
    commits: usize,
    files: usize,
    workspace_repos: usize,
    log_limit: u32,
    force: bool,
}

impl Default for Args {
    fn default() -> Self {
        Self {
            repo: PathBuf::from("target/fjord-bench/synthetic-repo"),
            commits: 200,
            files: 50,
            workspace_repos: 1,
            log_limit: 50,
            force: false,
        }
    }
}

fn parse_args() -> Result<Args, String> {
    let mut args = Args::default();
    let mut iter = env::args().skip(1);

    while let Some(arg) = iter.next() {
        match arg.as_str() {
            "--repo" => args.repo = PathBuf::from(next_value(&mut iter, "--repo")?),
            "--commits" => {
                args.commits = parse_usize(next_value(&mut iter, "--commits")?, "--commits")?
            }
            "--files" => args.files = parse_usize(next_value(&mut iter, "--files")?, "--files")?,
            "--workspace-repos" => {
                args.workspace_repos = parse_usize(
                    next_value(&mut iter, "--workspace-repos")?,
                    "--workspace-repos",
                )?
            }
            "--log-limit" => {
                args.log_limit = parse_u32(next_value(&mut iter, "--log-limit")?, "--log-limit")?
            }
            "--force" => args.force = true,
            "--help" | "-h" => return Err(usage()),
            other => return Err(format!("unknown argument: {other}\n\n{}", usage())),
        }
    }

    if args.commits == 0 {
        return Err("--commits must be at least 1".to_string());
    }
    if args.files == 0 {
        return Err("--files must be at least 1".to_string());
    }
    if args.workspace_repos == 0 {
        return Err("--workspace-repos must be at least 1".to_string());
    }

    Ok(args)
}

fn next_value(iter: &mut impl Iterator<Item = String>, flag: &str) -> Result<String, String> {
    iter.next()
        .ok_or_else(|| format!("{flag} requires a value\n\n{}", usage()))
}

fn parse_usize(value: String, flag: &str) -> Result<usize, String> {
    value
        .parse()
        .map_err(|_| format!("{flag} must be a positive integer"))
}

fn parse_u32(value: String, flag: &str) -> Result<u32, String> {
    value
        .parse()
        .map_err(|_| format!("{flag} must be a positive integer"))
}

fn usage() -> String {
    "Usage: cargo run -p fjord-bench -- [--repo PATH] [--commits N] [--files N] [--workspace-repos N] [--log-limit N] [--force]".to_string()
}

fn prepare_repo_dir(path: &Path, force: bool) -> Result<bool, String> {
    if !path.exists() {
        fs::create_dir_all(path).map_err(|e| e.to_string())?;
        return Ok(true);
    }

    if path.join(".git").exists() && !force {
        return Ok(false);
    }

    if force {
        if !path.join(MARKER_FILE).exists() {
            return Err(format!(
                "refusing to delete {}; missing {MARKER_FILE}",
                path.display()
            ));
        }
        fs::remove_dir_all(path).map_err(|e| e.to_string())?;
        fs::create_dir_all(path).map_err(|e| e.to_string())?;
        return Ok(true);
    }

    Err(format!(
        "{} exists but is not a generated git repository; choose another --repo path",
        path.display()
    ))
}

fn prepare_workspace_dir(path: &Path, force: bool) -> Result<bool, String> {
    if !path.exists() {
        fs::create_dir_all(path).map_err(|e| e.to_string())?;
        fs::write(path.join(MARKER_FILE), "generated by fjord-bench\n")
            .map_err(|e| e.to_string())?;
        return Ok(true);
    }

    if !path.join(MARKER_FILE).exists() {
        return Err(format!(
            "refusing to use {}; missing {MARKER_FILE}",
            path.display()
        ));
    }

    if force {
        fs::remove_dir_all(path).map_err(|e| e.to_string())?;
        fs::create_dir_all(path).map_err(|e| e.to_string())?;
        fs::write(path.join(MARKER_FILE), "generated by fjord-bench\n")
            .map_err(|e| e.to_string())?;
        return Ok(true);
    }

    Ok(false)
}

fn generate_repo(path: &Path, commits: usize, files: usize) -> Result<(), String> {
    fs::write(path.join(MARKER_FILE), "generated by fjord-bench\n").map_err(|e| e.to_string())?;

    let mut options = RepositoryInitOptions::new();
    options.initial_head("main");
    let repo = Repository::init_opts(path, &options).map_err(|e| e.message().to_string())?;
    let mut config = repo.config().map_err(|e| e.message().to_string())?;
    config
        .set_str("user.name", "Fjord Bench")
        .map_err(|e| e.message().to_string())?;
    config
        .set_str("user.email", "bench@example.com")
        .map_err(|e| e.message().to_string())?;

    for file_index in 0..files {
        write_bench_file(path, file_index, 0)?;
    }
    commit_all(&repo, "seed synthetic repository")?;

    for commit_index in 1..commits {
        write_bench_file(path, commit_index % files, commit_index)?;
        commit_all(&repo, &format!("synthetic commit {commit_index}"))?;
    }

    Ok(())
}

fn write_bench_file(repo: &Path, file_index: usize, commit_index: usize) -> Result<(), String> {
    let path = repo.join(format!("file-{file_index:04}.txt"));
    fs::write(
        path,
        format!("file {file_index}\nsynthetic revision {commit_index}\n"),
    )
    .map_err(|e| e.to_string())
}

fn commit_all(repo: &Repository, message: &str) -> Result<(), String> {
    let mut index = repo.index().map_err(|e| e.message().to_string())?;
    index
        .add_all(["*"], git2::IndexAddOption::DEFAULT, None)
        .map_err(|e| e.message().to_string())?;
    index.write().map_err(|e| e.message().to_string())?;
    let tree_oid = index.write_tree().map_err(|e| e.message().to_string())?;
    let tree = repo
        .find_tree(tree_oid)
        .map_err(|e| e.message().to_string())?;
    let signature =
        Signature::now("Fjord Bench", "bench@example.com").map_err(|e| e.message().to_string())?;
    let parent = repo.head().ok().and_then(|head| head.peel_to_commit().ok());
    let parents = parent.iter().collect::<Vec<_>>();

    repo.commit(
        Some("HEAD"),
        &signature,
        &signature,
        message,
        &tree,
        &parents,
    )
    .map(|_| ())
    .map_err(|e| e.message().to_string())
}

#[tokio::main]
async fn main() -> Result<(), String> {
    let args = parse_args()?;
    if args.workspace_repos > 1 {
        return run_workspace_benchmark(args).await;
    }

    let should_generate = prepare_repo_dir(&args.repo, args.force)?;

    if should_generate {
        generate_repo(&args.repo, args.commits, args.files)?;
    }

    let open_start = Instant::now();
    Repository::open(&args.repo).map_err(|e| e.message().to_string())?;
    let open_elapsed = open_start.elapsed();

    let backend = GixGitBackend::new();
    let repo = RepoPath::new(args.repo.clone());

    let status_start = Instant::now();
    let status = backend.status(&repo).await.map_err(|e| e.to_string())?;
    let status_elapsed = status_start.elapsed();

    let log_start = Instant::now();
    let log = backend
        .log(&repo, None, args.log_limit)
        .await
        .map_err(|e| e.to_string())?;
    let log_elapsed = log_start.elapsed();

    println!("repo={}", args.repo.display());
    println!("generated={should_generate}");
    println!("commits={}", args.commits);
    println!("files={}", args.files);
    println!(
        "branch={}",
        status.branch.unwrap_or_else(|| "(detached)".to_string())
    );
    println!("dirty_count={}", status.dirty_count);
    println!("has_conflict={}", status.has_conflict);
    println!("log_commits={}", log.commits.len());
    println!("open_ms={:.3}", open_elapsed.as_secs_f64() * 1000.0);
    println!("status_ms={:.3}", status_elapsed.as_secs_f64() * 1000.0);
    println!("log_ms={:.3}", log_elapsed.as_secs_f64() * 1000.0);

    Ok(())
}

async fn run_workspace_benchmark(args: Args) -> Result<(), String> {
    let generated = prepare_workspace_dir(&args.repo, args.force)?;

    let backend = GixGitBackend::new();
    let pool = fjord_db::connect(Path::new(":memory:"))
        .await
        .map_err(|e| e.to_string())?;
    let store = SqliteWorkspaceStore::new(pool);
    let workspace = store
        .create_workspace("Synthetic workspace")
        .await
        .map_err(|e| e.to_string())?;

    let generation_start = Instant::now();
    let mut repositories = Vec::new();
    for index in 0..args.workspace_repos {
        let repo_path = args.repo.join(format!("repo-{index:02}"));
        let should_generate_repo = prepare_repo_dir(&repo_path, args.force)?;
        if generated || should_generate_repo {
            generate_repo(&repo_path, args.commits, args.files)?;
        }

        let entry = store
            .add_repository(
                workspace.id,
                &format!("repo-{index:02}"),
                repo_path.as_path(),
            )
            .await
            .map_err(|e| e.to_string())?;
        repositories.push(entry);
    }
    let generation_elapsed = generation_start.elapsed();

    let live_refresh_start = Instant::now();
    for repo in &repositories {
        let status = backend
            .status(&RepoPath::new(repo.path.clone()))
            .await
            .map_err(|e| e.to_string())?;
        store
            .upsert_repo_status(repo.id, &status)
            .await
            .map_err(|e| e.to_string())?;
    }
    let live_refresh_elapsed = live_refresh_start.elapsed();

    let cached_dashboard_start = Instant::now();
    let dashboard = store
        .list_workspace_status(workspace.id)
        .await
        .map_err(|e| e.to_string())?;
    let cached_dashboard_elapsed = cached_dashboard_start.elapsed();

    let need_attention = dashboard
        .iter()
        .filter(|summary| {
            summary.status.has_conflict
                || summary.status.dirty_count > 0
                || summary.status.ahead > 0
                || summary.status.behind > 0
        })
        .count();
    let behind_origin = dashboard
        .iter()
        .filter(|summary| summary.status.behind > 0)
        .count();

    println!("workspace_root={}", args.repo.display());
    println!("generated={generated}");
    println!("workspace_repos={}", args.workspace_repos);
    println!("commits_per_repo={}", args.commits);
    println!("files_per_repo={}", args.files);
    println!("dashboard_rows={}", dashboard.len());
    println!("need_attention={need_attention}");
    println!("behind_origin={behind_origin}");
    println!(
        "generation_ms={:.3}",
        generation_elapsed.as_secs_f64() * 1000.0
    );
    println!(
        "live_refresh_ms={:.3}",
        live_refresh_elapsed.as_secs_f64() * 1000.0
    );
    println!(
        "cached_dashboard_ms={:.3}",
        cached_dashboard_elapsed.as_secs_f64() * 1000.0
    );

    Ok(())
}
